/**
 * Conference Ticketing API
 *
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateMembers400ResponseErrorsInner } from './createMembers400ResponseErrorsInner';


export interface CreateMembers400Response { 
    errors?: Array<CreateMembers400ResponseErrorsInner>;
}

